import type { Metadata } from "next";
import { inter } from "./fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "restcountries",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden`}>{children}</body>
    </html>
  );
}
